services:
  kmua:
    image: ghcr.io/krau/kmua-bot:v2
    container_name: kmua-bot
    restart: unless-stopped
    volumes:
      - ./data:/kmua/data
      - ./logs:/kmua/logs
      - ./settings.toml:/kmua/settings.toml
    environment:
      - TZ=Asia/Shanghai
    network_mode: host