version: "3"
services:
  kmua:
    image: ghcr.io/krau/kmua-bot:v2
    container_name: kmua-v2-main
    restart: always
    volumes:
      - ./data:/kmua/data # 不要修改此挂载
      - ./logs:/kmua/logs
    environment:
      - TZ=Asia/Shanghai
      - KMUA_TOKEN="你的token"
      - KMUA_OWNERS=[]
      - KMUA_LOG_LEVEL="INFO"