[project]
name = "kmua-bot"
version = "2.9.0"
description = "A Telegram Bot"
readme = "README.md"
license = "AGPL-3.0"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "dynaconf>=3.2.11",
    "kurigram>=2.2.3",
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
    "pyyaml>=6.0.2",
    "sqlalchemy[asyncio]>=2.0.41",
    "tgcrypto>=1.2.5",
    "uvloop>=0.21.0",
]

[tool.uv]
dev-dependencies = ["ruff>=0.9.3"]

[tool.ruff]
lint.select = ["I"]
