[tool.poetry]
name = "kmua-bot-pyro"
version = "0.1.0"
description = ""
authors = ["krau <me@krau.top>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyrogram = {git = "https://github.com/KurimuzonAkuma/pyrogram.git"}
tgcrypto = "^1.2.5"
loguru = "^0.7.2"
dynaconf = "^3.2.4"
sqlalchemy = "^2.0.25"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
