[project]
name = "kmua-bot"
version = "2.9.0"
description = "A Telegram Bot"
readme = "README.md"
license = "AGPL-3.0"
requires-python = ">=3.13"
dependencies = [
    "aiocache[redis]>=0.12.3",
    "aiofiles>=24.1.0",
    "aiosqlite>=0.21.0",
    "alembic>=1.16.1",
    "apscheduler>=3.11.0",
    "asyncpg>=0.30.0",
    "dynaconf>=3.2.11",
    "emoji==2.11",
    "graphviz>=0.20.3",
    "httpx>=0.28.1",
    "kurigram>=2.2.3",
    "loguru>=0.7.3",
    "orjson>=3.10.18",
    "pillow>=11.2.1",
    "pilmoji>=2.0.4",
    "pydantic>=2.11.4",
    "pydantic-ai",
    "pyyaml>=6.0.2",
    "redis>=6.2.0",
    "sqlalchemy[asyncio]>=2.0.41",
    "tgcrypto>=1.2.5",
    "uvloop>=0.21.0",
    "wordcloud>=1.9.4",
    "zhconv>=1.4.3",
]

[tool.ruff]
lint.select = ["I"]

[tool.uv.sources]
pydantic-ai = { git = "https://github.com/krau/pydantic-ai.git" }
