token = ""
owners = []
db_url = "sqlite+aiosqlite:///./data/kmua.db"
session_name = "kmua"
api_id = 1025907
api_hash = "452b0359b988148995f22ff0f4229750"
use_ipv6 = false
log_retention_days = 30
log_level = "INFO"
lang = "zh-CN"

redis = false
redis_endpoint = "localhost"
redis_port = 6379
redis_db = 0
redis_password = ""

agent = false
agent_model = "gpt-4o-mini"
agent_provider_url = "https://api.openai.com/v1"
agent_api_key = ""
agent_messages_threshold = 20
agent_whitelist_mode = false
agent_whitelist = []
agent_prompt = ''''''

manyacg_api_url = "https://api.manyacg.top/v1"
manyacg_api_key = ""
manyacg_channel = "MoreACG"
manyacg_bot = "kirakabot"
manyacg_setu_cd = 1
manyacg_hybrid_search = true

# Periodic sticker / reaction: force the model to call the tool every N conversations.
# Set to 0 to disable.
# agent_periodic_sticker_interval = 5
# agent_periodic_reaction_interval = 3
