"""add user config

Revision ID: 3ebc67720b00
Revises: a7203cd2ce37
Create Date: 2025-05-23 09:53:05.164129

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ebc67720b00"
down_revision: Union[str, None] = "a7203cd2ce37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column("user_data", sa.Column("config", sa.JSON(), nullable=True))
    except Exception as e:
        print(e)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column("user_data", "config")
    except Exception as e:
        print(e)
    # ### end Alembic commands ###
