"""add promoted by

Revision ID: 78b495161626
Revises:
Create Date: 2025-06-07 10:11:10.011997

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78b495161626"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    insp = sa.inspect(bind)

    table_name = "user_chat_association"
    column_name = "promoted_by"

    # 检查: 存在表, 且不存在列
    if insp.has_table(table_name):
        existing_cols = {col["name"] for col in insp.get_columns(table_name)}
        if column_name not in existing_cols:
            op.add_column(
                table_name,
                sa.Column(column_name, sa.BigInteger(), nullable=True),
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_chat_association", "promoted_by")
    # ### end Alembic commands ###
