"""add username to ChatData

Revision ID: 798a99eb0695
Revises: 02360c28943f
Create Date: 2024-07-31 00:14:19.037054

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "798a99eb0695"
down_revision: Union[str, None] = "02360c28943f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column(
            "chat_data", sa.Column("username", sa.String(length=64), nullable=True)
        )
    except Exception as e:
        print(e)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column("chat_data", "username")
    except Exception as e:
        print(e)
    # ### end Alembic commands ###
