"""floating_bottle

Revision ID: d327932d860e
Revises: 78b495161626
Create Date: 2025-10-30 11:53:29.917280

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d327932d860e"
down_revision: str | None = "78b495161626"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    table_name = "bottles"
    if insp.has_table(table_name):
        return
    op.create_table(
        "bottles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sender_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.String(length=4096), nullable=True),
        sa.Column("picks", sa.BigInteger(), nullable=False),
        sa.Column("reports", sa.BigInteger(), nullable=False),
        sa.Column("file_id", sa.String(length=256), nullable=True),
        sa.Column("media_type", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_picked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["sender_id"], ["user_data.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bottles_id"), "bottles", ["id"], unique=False)
    op.create_index(
        op.f("ix_bottles_sender_id"), "bottles", ["sender_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bottles_sender_id"), table_name="bottles")
    op.drop_index(op.f("ix_bottles_id"), table_name="bottles")
    op.drop_table("bottles")
    # ### end Alembic commands ###
