/// <reference types="vite/client" />

interface ImportMetaEnv {
  /**
   * Signed Telegram initData for browser development, from `webapp/.env.local`.
   *
   * Generated by `scripts/dev_init_data.py`. Read only under `import.meta.env.DEV`,
   * so it cannot reach a production bundle.
   */
  readonly VITE_DEV_INIT_DATA?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

declare module "*.vue" {
  import type { DefineComponent } from "vue";

  const component: DefineComponent<Record<string, unknown>, Record<string, unknown>, unknown>;
  export default component;
}
